from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / ".test-deps"))

from playwright.sync_api import sync_playwright

BASE_URL = "http://127.0.0.1:4173"
ARTIFACTS = PROJECT_ROOT / "test-artifacts"
ARTIFACTS.mkdir(exist_ok=True)


def screenshot(page, name, full_page=True):
    page.screenshot(path=str(ARTIFACTS / name), full_page=full_page)


with sync_playwright() as p:
    print("Launching browser", flush=True)
    browser = p.chromium.launch(
        headless=True,
        executable_path="C:/Program Files/Google/Chrome/Application/chrome.exe",
        args=["--no-sandbox", "--disable-gpu", "--disable-dev-shm-usage"],
    )

    mobile = browser.new_context(viewport={"width": 390, "height": 844}, device_scale_factor=1)
    page = mobile.new_page()
    page.set_default_timeout(10000)
    console_errors = []
    page.on("console", lambda msg: console_errors.append(msg.text) if msg.type == "error" else None)
    page.goto(BASE_URL, wait_until="domcontentloaded", timeout=15000)
    print("Mobile login loaded", flush=True)
    page.evaluate("localStorage.clear()")
    page.reload()
    page.wait_for_load_state("domcontentloaded")

    assert page.get_by_role("heading", name="เข้าสู่ระบบ").is_visible()
    screenshot(page, "01-login-mobile.png")
    page.get_by_label("ชื่อผู้ใช้").fill("BAD001")
    page.get_by_label("PIN 4 หลัก").fill("0000")
    page.get_by_role("button", name="เข้าสู่ระบบ").click()
    page.get_by_role("alert").filter(has_text="ชื่อผู้ใช้หรือ PIN ไม่ถูกต้อง").wait_for()
    page.get_by_label("ชื่อผู้ใช้").fill("DM001")
    page.get_by_label("PIN 4 หลัก").fill("1234")
    page.get_by_role("button", name="เข้าสู่ระบบ").click()
    page.get_by_role("heading", name="สวัสดี คุณสมใจ").wait_for()
    print("Patient home loaded", flush=True)
    assert page.evaluate("document.documentElement.scrollWidth <= window.innerWidth")
    page.locator(".profile-button").click()
    page.get_by_role("menuitem", name="ข้อมูลของฉัน").click()
    page.get_by_role("heading", name="ข้อมูลของฉัน", exact=True).wait_for()
    page.get_by_role("dialog").get_by_role("button", name="ปิด").first.click()
    page.locator(".profile-button").click()
    page.get_by_role("menuitem", name="การช่วยเหลือการใช้งาน").click()
    page.get_by_role("heading", name="ใช้งานได้ง่ายสำหรับทุกคน", exact=True).wait_for()
    page.get_by_role("dialog").get_by_role("button", name="ปิด").first.click()
    screenshot(page, "02-home-mobile.png")
    page.evaluate("localStorage.setItem('dmfc-examination-draft-v1', JSON.stringify({stage:'capture',step:1,photos:{'left-dorsal':'demo'},updatedAt:Date.now()}))")
    page.reload(wait_until="domcontentloaded")
    page.wait_for_load_state("networkidle")
    page.get_by_role("button", name="ทำต่อจากเดิม").wait_for()
    page.wait_for_timeout(500)
    screenshot(page, "02b-resume-draft-mobile.png")
    page.evaluate("localStorage.removeItem('dmfc-examination-draft-v1')")
    page.reload(wait_until="domcontentloaded")
    page.wait_for_load_state("networkidle")
    page.get_by_role("heading", name="สวัสดี คุณสมใจ").wait_for()

    page.get_by_role("button", name="เริ่มตรวจเท้า").click()
    page.get_by_role("heading", name="เตรียมถ่ายภาพเท้า 4 มุม").wait_for()
    page.get_by_role("button", name="เปิดกล้องและเริ่มถ่าย").click()
    page.get_by_role("button", name="ถ่ายภาพ").wait_for()
    page.wait_for_timeout(350)
    assert page.locator(".camera-viewport").is_visible()
    page.wait_for_timeout(3200)
    assert page.locator(".camera-permission-error").is_visible() or page.locator(".camera-preview").is_visible()
    screenshot(page, "03-capture-camera-mobile.png", full_page=False)

    for index in range(4):
        page.get_by_role("button", name="ใช้ภาพตัวอย่างสำหรับทดลอง").click()
        if index < 3:
            page.get_by_role("button", name="ใช้ภาพนี้และถ่ายภาพต่อไป").click()
        else:
            page.get_by_role("button", name="ตรวจดูภาพทั้งหมด").click()

    page.get_by_role("heading", name="ภาพเท้าครบทั้ง 4 มุม").wait_for()
    screenshot(page, "04-photo-review-mobile.png")
    mobile.set_offline(True)
    page.get_by_role("button", name="ประเมินผล").click()
    page.get_by_role("alert").filter(has_text="ไม่มีอินเทอร์เน็ต").wait_for()
    mobile.set_offline(False)
    page.get_by_role("button", name="ลองประเมินอีกครั้ง").wait_for()
    page.get_by_role("button", name="ลองประเมินอีกครั้ง").click()
    page.get_by_role("heading", name="AI แนะนำ 2 รายการ").wait_for(timeout=6000)
    page.get_by_text("AI แนะนำ: พบ · มั่นใจ 91%").wait_for()
    page.get_by_role("button", name="ดูหลังเท้าซ้าย").click()
    page.get_by_role("heading", name="หลังเท้าซ้าย", exact=True).wait_for()
    page.get_by_role("dialog").get_by_role("button", name="กลับไปตรวจผล").click()
    # Change only the confirmed severity; the original AI suggestion remains visible for auditability.
    page.locator(".severity-select select").first.select_option(label="รุนแรง")
    print("Human review loaded", flush=True)
    screenshot(page, "05-human-review-mobile.png")
    page.get_by_role("button", name="ยืนยันและส่งผลตรวจ").click()
    page.get_by_role("heading", name="ผลการตรวจเท้า").wait_for()
    assert page.locator(".summary-photo-grid .summary-photo").count() == 4
    assert page.locator(".summary-page .severity-label", has_text="รุนแรง").count() >= 1
    summary_date = page.locator(".summary-date").inner_text().split(" · ")[0]
    page.wait_for_timeout(150)
    summary_scroll = page.evaluate("window.scrollY")
    active_element = page.evaluate("document.activeElement && document.activeElement.className")
    print(f"Summary scroll position: {summary_scroll}; active element: {active_element}", flush=True)
    assert summary_scroll == 0
    screenshot(page, "06-summary-mobile.png", full_page=False)
    assert page.evaluate("document.documentElement.scrollWidth <= window.innerWidth")

    page.get_by_role("button", name="กลับหน้าหลัก").click()
    assert page.locator("#latest-title").inner_text() == summary_date
    assert page.locator(".latest-card .result-count strong").inner_text() == "2"
    page.get_by_role("button", name="ประวัติ").last.click()
    page.get_by_role("heading", name="ประวัติการตรวจ").wait_for()
    page.get_by_text("ตรวจแล้ว 5 ครั้ง", exact=True).wait_for()
    page.locator(".exam-card").first.get_by_text("พบ 2 รายการ", exact=True).wait_for()
    assert page.locator(".exam-card").first.locator(".exam-thumb.has-image").count() == 1
    page.locator(".exam-card").first.get_by_role("button", name=f"ดูผลวันที่ {summary_date}").click()
    page.get_by_role("heading", name=f"ผลตรวจวันที่ {summary_date}", exact=True).wait_for()
    assert page.locator(".detail-photo-row .has-thumbnail").count() == 4
    page.get_by_role("dialog").get_by_role("button", name="ปิดรายละเอียด").click()
    page.get_by_role("tab", name="แนวโน้ม").click()
    page.get_by_text("ภาพรวมจาก 5 ครั้งล่าสุด", exact=True).wait_for()
    assert page.locator(".insight-grid").is_visible()
    page.get_by_role("tab", name="รายการ").click()
    screenshot(page, "07-history-mobile.png")
    page.get_by_role("tab", name="ปฏิทิน").click()
    assert page.get_by_role("heading", name="สิงหาคม 2569", exact=True).is_visible()
    page.get_by_role("button", name="คลังความรู้").last.click()
    page.get_by_role("heading", name="คลังความรู้ดูแลเท้า").wait_for()
    page.get_by_label("กรองตามภาวะ").select_option("D003")
    page.get_by_role("heading", name="แผลแบบไหนไม่ควรรอดูอาการ").wait_for()
    page.get_by_label("กรองตามระดับความรุนแรง").select_option(label="เล็กน้อย")
    page.get_by_role("heading", name="ยังไม่พบหัวข้อนี้").wait_for()
    page.get_by_role("button", name="ดูบทความทั้งหมด").click()
    screenshot(page, "08-knowledge-mobile.png")
    assert not console_errors, f"Browser console errors: {console_errors}"
    mobile.close()
    print("Patient flow passed", flush=True)

    desktop = browser.new_context(viewport={"width": 1440, "height": 1000}, device_scale_factor=1)
    admin = desktop.new_page()
    admin.set_default_timeout(10000)
    admin.goto(BASE_URL, wait_until="domcontentloaded", timeout=15000)
    admin.evaluate("localStorage.clear()")
    admin.reload()
    admin.wait_for_load_state("domcontentloaded")
    admin.get_by_label("ชื่อผู้ใช้").fill("DMDR01")
    admin.get_by_label("PIN 4 หลัก").fill("1234")
    admin.get_by_role("button", name="เข้าสู่ระบบ").click()
    admin.get_by_role("heading", name="สวัสดี พญ. มาลี").wait_for()
    print("Doctor workspace loaded", flush=True)
    assert admin.evaluate("document.documentElement.scrollWidth <= window.innerWidth")
    admin.get_by_role("button", name="พญ. มาลี สุขใจ").click()
    admin.get_by_role("menu").wait_for()
    admin.keyboard.press("Escape")
    assert not admin.get_by_role("menu").is_visible()
    admin.get_by_role("button", name="ดู สมใจ ใจดี").click()
    admin.get_by_role("heading", name="ผลตรวจวันที่ 8 ส.ค. 2569", exact=True).wait_for()
    admin.get_by_role("dialog").get_by_label("ปิด", exact=True).click()
    screenshot(admin, "09-doctor-desktop.png")
    admin.get_by_role("button", name="ผู้ใช้งาน", exact=True).first.click()
    admin.get_by_role("heading", name="ผู้ใช้งาน", exact=True).wait_for()
    admin.get_by_role("button", name="เพิ่มผู้ใช้งาน").click()
    admin.get_by_role("heading", name="เพิ่มผู้ใช้งาน", exact=True).wait_for()
    admin.get_by_label("Username").fill("DM005")
    admin.get_by_label("ชื่อ-นามสกุล").fill("ทดสอบ เพิ่มผู้ใช้")
    admin.get_by_label("วันเดือนปีเกิด").fill("1980-01-01")
    admin.get_by_label("อาชีพ").fill("พนักงาน")
    admin.get_by_label("PIN เริ่มต้น (4 หลัก)").fill("2468")
    admin.get_by_role("button", name="บันทึกข้อมูล").click()
    admin.get_by_text("เพิ่มผู้ใช้ DM005 แล้ว").wait_for()
    admin.get_by_text("Gen X", exact=False).first.wait_for()
    admin.get_by_role("button", name="ดูประวัติ").first.click()
    admin.get_by_role("heading", name="สมใจ ใจดี", exact=True).wait_for()
    admin.locator(".user-history-card").first.click()
    admin.get_by_role("heading", name="ผลตรวจวันที่ 8 ส.ค. 2569", exact=True).wait_for()
    admin.get_by_role("dialog").last.get_by_label("ปิด", exact=True).click()
    admin.get_by_role("button", name="ปิดประวัติ").click()
    admin.get_by_role("button", name="แก้ไข").first.click()
    admin.get_by_role("button", name="รีเซ็ต PIN").click()
    admin.get_by_text("สร้าง PIN ใหม่สำหรับ DM001 แล้ว").wait_for()
    admin.get_by_role("dialog").get_by_role("button", name="ปิด").click()
    admin.get_by_role("button", name="รายการภาวะ").click()
    admin.get_by_role("heading", name="Disease Master").wait_for()
    admin.get_by_role("button", name="เพิ่มรายการ").click()
    admin.get_by_role("heading", name="เพิ่มรายการภาวะ", exact=True).wait_for()
    admin.get_by_label("ชื่อภาวะ").fill("ตาปลา")
    admin.get_by_label("หมวดหมู่").fill("ผิวหนัง")
    admin.get_by_label("คำอธิบาย").fill("ผิวหนาเฉพาะจุดจากแรงกด")
    admin.get_by_label("เกณฑ์ตรวจจับ").fill("พบผิวหนาแข็งเฉพาะจุด")
    admin.locator("#disease-severity-1").fill("จุดเล็กและไม่เจ็บ")
    admin.locator("#disease-severity-2").fill("หนาหลายจุดหรือเริ่มเจ็บ")
    admin.locator("#disease-severity-3").fill("เจ็บมากหรือมีแผลใต้หนังด้าน")
    admin.get_by_label("คำแนะนำการดูแล").fill("เลือกรองเท้าที่ไม่กดทับและปรึกษาแพทย์")
    admin.get_by_label("การรักษา / คำแนะนำเพิ่มเติม").fill("หากเจ็บมากให้พบแพทย์")
    admin.get_by_role("button", name="บันทึกเกณฑ์").click()
    admin.get_by_text("เพิ่ม ตาปลา แล้ว").wait_for()
    admin.get_by_text("จุดเล็กและไม่เจ็บ", exact=False).first.wait_for()
    admin.get_by_text("เจ็บมากหรือมีแผลใต้หนังด้าน", exact=False).first.wait_for()
    admin.get_by_role("button", name="แก้ไขเกณฑ์").first.click()
    admin.get_by_role("dialog").get_by_role("button", name="ยกเลิก").click()
    screenshot(admin, "10-disease-master-desktop.png")
    admin.get_by_role("button", name="คลังความรู้", exact=True).click()
    admin.get_by_role("heading", name="จัดการคลังความรู้", exact=True).wait_for()
    admin.get_by_role("button", name="สร้างบทความ").click()
    admin.get_by_role("heading", name="สร้างบทความ", exact=True).wait_for()
    admin.get_by_label("ชื่อบทความ").fill("ดูแลเท้าหลังตรวจ")
    admin.get_by_label("เชื่อมกับภาวะ").select_option("D001")
    admin.get_by_label("ระดับ").select_option(label="ปานกลาง")
    admin.get_by_label("หมวดหมู่").fill("การติดตาม")
    admin.get_by_label("สรุปสั้น").fill("คำแนะนำหลังดูผลตรวจและการสังเกตอาการ")
    admin.locator('input[placeholder="ขั้นตอนที่ 1"]').fill("ตรวจเท้าทุกวัน")
    admin.locator('input[placeholder="ขั้นตอนที่ 2"]').fill("จดบันทึกความเปลี่ยนแปลง")
    admin.get_by_label("การรักษา").fill("ใช้ครีมตามคำแนะนำของแพทย์")
    admin.get_by_label("คำแนะนำเพิ่มเติม").fill("หากมีแผลให้ติดต่อแพทย์")
    admin.get_by_role("button", name="บันทึกบทความ").click()
    admin.get_by_text("สร้างบทความ “ดูแลเท้าหลังตรวจ” แล้ว").wait_for()
    admin.get_by_role("button", name="แก้ไข").last.click()
    assert admin.get_by_label("เชื่อมกับภาวะ").input_value() == "D001"
    assert admin.get_by_label("ระดับ").input_value() == "ปานกลาง"
    admin.get_by_role("dialog").get_by_role("button", name="ยกเลิก").click()
    screenshot(admin, "11-knowledge-admin-desktop.png")
    desktop.close()
    browser.close()

print("DMFC smoke test passed: patient golden path, history, knowledge, and doctor workspace")
