import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const app = read('src/App.tsx')
const types = read('src/types.ts')
const register = read('backend/api/v1/auth/register.mjs')
const adminKnowledge = read('backend/api/v1/admin/knowledge.mjs')
const publicKnowledge = read('backend/api/v1/knowledge.mjs')
const adminVideos = read('backend/api/v1/admin/care-videos.mjs')
const publicVideos = read('backend/api/v1/care-videos.mjs')
const main = read('src/main.tsx')
const css = read('src/accessibility-overrides.css')
const imageQuality = read('src/services/imageQuality.ts')
const liveCapture = read('src/services/liveCapture.ts')
const adminDashboard = read('backend/api/v1/admin/dashboard.mjs')
const adminBootstrap = read('backend/api/v1/admin/bootstrap.mjs')

assert.match(types, /sex: Sex/)
assert.match(types, /diabetesYears: number/)
assert.match(types, /latestHba1c\?: number/)
assert.match(register, /account_status: 'active'/)
assert.match(register, /diabetes_years: input\.diabetesYears/)
assert.match(register, /latest_hba1c: input\.latestHba1c/)
assert.doesNotMatch(register, /status: 'pending'/)
assert.match(app, /เป็นเบาหวานมาแล้วกี่ปี/)
assert.match(app, /HbA1c ล่าสุด/)
assert.match(app, /คำแนะนำการดูแลเท้า/)
assert.match(app, /วิดีโอแนะนำ/)
assert.doesNotMatch(app, /เปิดวิดีโอ YouTube/)
assert.match(app, /draft\.care\.map/)
assert.doesNotMatch(app, /\[0, 1, 2\]\.map/)
assert.doesNotMatch(adminKnowledge, /youtubeUrl/)
assert.doesNotMatch(publicKnowledge, /youtubeUrl/)
assert.match(adminVideos, /normalizeYoutubeUrl/)
assert.match(adminVideos, /dmfc-knowledge-media/)
assert.match(publicVideos, /care_videos/)
assert.match(main, /accessibility-overrides\.css/)
assert.match(css, /font-size: 17px/)
assert.match(app, /ถ่ายด้วยตนเอง/)
assert.match(app, /ให้ผู้อื่นช่วยถ่าย/)
assert.match(app, /เสียงแนะนำ/)
assert.match(app, /กำลังบันทึกอัตโนมัติ/)
assert.match(app, /const targetStableFrames = 3/)
assert.match(app, /unstableFramesRef\.current > 1/)
assert.match(app, /readyLatchedRef\.current = true/)
assert.match(app, /performance\.now\(\) \+ 900/)
assert.match(app, /if \(!captureInProgressRef\.current\) void capturePhoto\(\)/)
assert.doesNotMatch(app, /stableFramesRef\.current >= 4/)
assert.match(types, /allExaminations\?: AdminDashboardRecentExam\[\]/)
assert.match(adminDashboard, /const orderedConfirmed = \[\.\.\.confirmed\]\.sort/)
assert.match(adminDashboard, /allExaminations/)
assert.match(adminBootstrap, /allExaminations/)
assert.match(app, /ประวัติการตรวจทั้งหมด/)
assert.match(app, /เรียงจากใหม่ไปเก่า/)
assert.match(app, /ยังรอสิทธิ์กล้อง/)
assert.match(app, /กรุณาตรวจทานก่อนใช้ต่อ/)
assert.match(app, /ภาพพร้อมตรวจ/)
assert.doesNotMatch(app, /setCameraState\('denied'\)\n {6}}\n {4}}, 3000/)
assert.match(css, /DMFC mobile visual-viewport fit/)
assert.match(css, /min-inline-size: 100vw/)
assert.match(app, /ถ่ายเองหากระบบสแกนไม่สำเร็จ/)
assert.match(app, /ผลประเมินเบื้องต้น/)
assert.doesNotMatch(app, /AI แนะนำ: .*มั่นใจ/)
assert.match(imageQuality, /gate: 'ready' \| 'warning' \| 'block'/)
assert.match(liveCapture, /evaluateLiveFrameReadiness/)
// Every view must get fresh capture refs, timers and progress; otherwise the
// previous view's captureInProgress latch freezes the next view at 100%.
assert.match(app, /<CaptureStep key=\{footSteps\[step\]\.id\}/)
const cameraViewport = app.slice(app.indexOf('<div className={photo ?'), app.indexOf('<div className="capture-controls">'))
assert.match(cameraViewport, /scan-progress-overlay/)
assert.match(cameraViewport, /\{scanProgress\}%/)
assert.match(cameraViewport, /\{current\.hint\}/)
const steps = read('src/data.ts')
assert.match(steps, /id: 'left-sole'/)
assert.match(steps, /id: 'right-sole'/)
console.log('DMFC feature update contract passed')

assert.match(types, /export interface CareVideo/)
assert.match(types, /'videos'/)
assert.match(types, /'admin-videos'/)
const knowledgeArticleBlock = types.match(/export interface KnowledgeArticle \{[\s\S]*?\n\}/)?.[0] ?? ''
assert.doesNotMatch(knowledgeArticleBlock, /youtubeUrl/)
assert.match(app, /วิดีโอแนะนำการดูแลเท้า/)
assert.match(app, /function CareVideoPage/)
assert.match(app, /function VideoManagement/)
assert.match(app, /youtube-nocookie\.com\/embed/)
assert.match(app, /<iframe/)
assert.match(css, /\.care-video-grid/)
assert.match(css, /repeat\(5/)
console.log('Dedicated care video system contract passed')
