import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const app = read('src/App.tsx')
const types = read('src/types.ts')
const register = read('backend/api/v1/auth/register.mjs')
const adminKnowledge = read('backend/api/v1/admin/knowledge.mjs')
const publicKnowledge = read('backend/api/v1/knowledge.mjs')
const main = read('src/main.tsx')
const css = read('src/accessibility-overrides.css')

assert.match(types, /sex: Sex/)
assert.match(types, /diabetesYears: number/)
assert.match(types, /latestHba1c\?: number/)
assert.match(register, /account_status: 'active'/)
assert.match(register, /diabetes_years: input\.diabetesYears/)
assert.match(register, /latest_hba1c: input\.latestHba1c/)
assert.doesNotMatch(register, /status: 'pending'/)
assert.match(app, /เป็นเบาหวานมาแล้วกี่ปี/)
assert.match(app, /HbA1c ล่าสุด/)
assert.match(app, /คำแนะนำการดูแลเท้า/)
assert.match(app, /วิดีโอแนะนำ/)
assert.match(app, /draft\.care\.map/)
assert.doesNotMatch(app, /\[0, 1, 2\]\.map/)
assert.match(adminKnowledge, /normalizeYoutubeUrl/)
assert.match(adminKnowledge, /youtubeUrl/)
assert.match(publicKnowledge, /youtubeUrl/)
assert.match(main, /accessibility-overrides\.css/)
assert.match(css, /\.knowledge-mode-tabs/)
assert.match(css, /font-size: 17px/)
console.log('DMFC feature update contract passed')
