import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const app = read('src/App.tsx')
const types = read('src/types.ts')
const register = read('backend/api/v1/auth/register.mjs')
const adminKnowledge = read('backend/api/v1/admin/knowledge.mjs')
const publicKnowledge = read('backend/api/v1/knowledge.mjs')
const adminVideos = read('backend/api/v1/admin/care-videos.mjs')
const publicVideos = read('backend/api/v1/care-videos.mjs')
const main = read('src/main.tsx')
const css = read('src/accessibility-overrides.css')

assert.match(types, /sex: Sex/)
assert.match(types, /diabetesYears: number/)
assert.match(types, /latestHba1c\?: number/)
assert.match(register, /account_status: 'active'/)
assert.match(register, /diabetes_years: input\.diabetesYears/)
assert.match(register, /latest_hba1c: input\.latestHba1c/)
assert.doesNotMatch(register, /status: 'pending'/)
assert.match(app, /เป็นเบาหวานมาแล้วกี่ปี/)
assert.match(app, /HbA1c ล่าสุด/)
assert.match(app, /คำแนะนำการดูแลเท้า/)
assert.match(app, /วิดีโอแนะนำ/)
assert.doesNotMatch(app, /เปิดวิดีโอ YouTube/)
assert.match(app, /draft\.care\.map/)
assert.doesNotMatch(app, /\[0, 1, 2\]\.map/)
assert.doesNotMatch(adminKnowledge, /youtubeUrl/)
assert.doesNotMatch(publicKnowledge, /youtubeUrl/)
assert.match(adminVideos, /normalizeYoutubeUrl/)
assert.match(adminVideos, /dmfc-knowledge-media/)
assert.match(publicVideos, /care_videos/)
assert.match(main, /accessibility-overrides\.css/)
assert.match(css, /font-size: 17px/)
console.log('DMFC feature update contract passed')

assert.match(types, /export interface CareVideo/)
assert.match(types, /'videos'/)
assert.match(types, /'admin-videos'/)
const knowledgeArticleBlock = types.match(/export interface KnowledgeArticle \{[\s\S]*?\n\}/)?.[0] ?? ''
assert.doesNotMatch(knowledgeArticleBlock, /youtubeUrl/)
assert.match(app, /วิดีโอแนะนำการดูแลเท้า/)
assert.match(app, /function CareVideoPage/)
assert.match(app, /function VideoManagement/)
assert.match(app, /youtube-nocookie\.com\/embed/)
assert.match(app, /<iframe/)
assert.match(css, /\.care-video-grid/)
assert.match(css, /repeat\(5/)
console.log('Dedicated care video system contract passed')
