import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const migrationPath = fileURLToPath(new URL('../supabase/migrations/20260808000000_create_dmfc_core.sql', import.meta.url))
const verificationPath = fileURLToPath(new URL('../supabase/verification/rls_invariants.sql', import.meta.url))
const migration = readFileSync(migrationPath, 'utf8')
const verification = readFileSync(verificationPath, 'utf8')

for (const table of ['profiles', 'user_roles', 'diseases', 'disease_severity_levels', 'examinations', 'examination_images', 'ai_analysis_runs', 'ai_findings', 'confirmed_findings', 'knowledge_articles', 'audit_logs']) {
  assert.match(migration, new RegExp(`alter table public\\.${table} enable row level security`), `RLS missing for ${table}`)
}

assert.match(migration, /unique \(examination_id, idempotency_key\)/)
assert.match(migration, /create table public\.ai_analysis_runs \([\s\S]*idempotency_key text not null/)
assert.match(migration, /'thumbnailing'.*'thumbnail_failed'/s)
assert.match(migration, /grant select on public\.audit_logs to authenticated/)
assert.match(migration, /grant usage on schema public to authenticated/)
assert.match(migration, /grant select on public\.profiles to authenticated/)
assert.match(migration, /grant select on public\.examinations, public\.examination_images, public\.confirmed_findings to authenticated/)
assert.match(migration, /grant select, insert, update on public\.diseases, public\.disease_severity_levels to authenticated/)
assert.match(migration, /grant select, insert, update on public\.knowledge_articles to authenticated/)
assert.doesNotMatch(migration, /audit_authenticated_insert/)
assert.doesNotMatch(migration, /grant select, insert on public\.audit_logs/)
assert.doesNotMatch(migration, /create policy "profiles_insert_own"/)
assert.doesNotMatch(migration, /create policy "examinations_insert_own"/)
assert.doesNotMatch(migration, /create policy "confirmed_insert_exam_owner_or_staff"/)
assert.doesNotMatch(migration, /thumbnail_insert_owner_or_staff/)
assert.doesNotMatch(migration, /thumbnail_update_owner_or_staff/)
assert.match(migration, /create trigger profiles_validate_date_of_birth/)
assert.match(migration, /create trigger examinations_validate_status/)
assert.match(migration, /requested_user = \(select auth\.uid\(\)\)/)
assert.match(migration, /old\.status = 'analysis_failed' and new\.status = 'uploading'/)
assert.match(migration, /old\.status = 'thumbnailing' and new\.status in \('confirmed', 'thumbnail_failed'\)/)
assert.doesNotMatch(migration, /date_of_birth date not null check \(date_of_birth <= current_date\)/)
assert.match(verification, /has_table_privilege\('authenticated', 'public\.audit_logs', 'INSERT'\)/)
assert.match(verification, /has_schema_privilege\('authenticated', 'public', 'USAGE'\)/)
assert.match(verification, /public\.knowledge_articles', 'SELECT,INSERT,UPDATE'/)
assert.match(verification, /public\.examinations', 'SELECT'/)
assert.match(migration, /values \('dm-foot-thumbnails', 'dm-foot-thumbnails', false\)/)
assert.match(migration, /'dmfc-disease-reference', 'dmfc-disease-reference', false/)
assert.match(migration, /'dmfc-knowledge-media', 'dmfc-knowledge-media', false/)
assert.match(verification, /All DMFC media buckets must exist and remain private/)
assert.match(verification, /disease_reference_staff_select/)
assert.match(verification, /disease_reference_staff_insert/)
assert.match(migration, /knowledge_media_published_or_staff_select/)
assert.match(verification, /knowledge_media_published_or_staff_select/)
assert.match(verification, /knowledge_media_staff_insert/)
assert.match(migration, /create or replace view private\.ai_accuracy_pairs/)
assert.match(migration, /comparison_result/)
assert.match(migration, /'false_positive'/)
assert.match(migration, /'false_negative'/)
assert.match(verification, /viewname = 'ai_accuracy_pairs'/)
assert.match(verification, /private\.ai_accuracy_pairs', 'SELECT'/)
assert.match(migration, /create or replace view private\.ai_accuracy_summary/)
assert.match(migration, /agreement_rate/)
assert.match(verification, /viewname = 'ai_accuracy_summary'/)
assert.match(verification, /private\.ai_accuracy_summary', 'SELECT'/)
assert.match(migration, /revoke all on table private\.ai_accuracy_pairs, private\.ai_accuracy_summary from public, anon, authenticated/)
assert.match(verification, /has_table_privilege\('anon', 'private\.ai_accuracy_pairs', 'SELECT'\)/)
assert.match(verification, /has_table_privilege\('anon', 'private\.ai_accuracy_summary', 'SELECT'\)/)

console.log('Schema invariant tests passed')
